# Generated by Django 5.2.8 on 2025-11-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name_of_product', models.CharField(max_length=10)),
                ('Categories', models.CharField(max_length=10)),
                ('Rate', models.IntegerField(max_length=10)),
                ('Manufacture_date', models.DateTimeField()),
                ('Expiredate', models.DateField()),
                ('Discount_of_product', models.IntegerField(max_length=2)),
            ],
        ),
    ]
